package Vista;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        

        jlEmpresa.setText("Restaurante Cali");
        jlIniSesion.setText("Iniciar Sesion");
        jlImUser.setText("");
        ImageIcon ImgUser = new ImageIcon(getClass().getResource("/imgs/cuenta.png"));
        Image EscalUser = ImgUser.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT);
        jlImUser.setIcon(new ImageIcon(EscalUser));
        
        jlUsuario.setText("Usuario");
        txtUsuario.setText("");
        txtUsuario.setToolTipText("Escriba su usuario");
        txtUsuario.setPreferredSize(new Dimension(150,30));
        jlPassword.setText("Contraseña");
        txtPassword.setText("");
        txtPassword.setToolTipText("Escriba su contraseña");
        txtPassword.setPreferredSize(new Dimension(150,30));

        btnLogeo.setText("Ingresar");
        btnLogeo.setToolTipText("Click Para Ingresar");
<<<<<<< HEAD
        btnLogeo.setMnemonic(0);
        

=======
>>>>>>> 629b0a4a0a07ad412eb64cf4714f8018caa7ca5d
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfFondo = new javax.swing.JPanel();
        jlIniSesion = new javax.swing.JLabel();
        jlEmpresa = new javax.swing.JLabel();
        jfIngreso = new javax.swing.JPanel();
        jlPassword = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        btnLogeo = new javax.swing.JButton();
        jlImUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlIniSesion.setText("jLabel1");

        jlEmpresa.setText("jLabel1");

        jlPassword.setText("jLabel2");

        jlUsuario.setText("jLabel1");

        txtPassword.setText("jPasswordField1");

        txtUsuario.setText("jTextField1");

        btnLogeo.setText("jButton1");
        btnLogeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogeoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfIngresoLayout = new javax.swing.GroupLayout(jfIngreso);
        jfIngreso.setLayout(jfIngresoLayout);
        jfIngresoLayout.setHorizontalGroup(
            jfIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfIngresoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jfIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUsuario)
                    .addComponent(jlPassword))
                .addGap(85, 85, 85)
                .addGroup(jfIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogeo)
                    .addGroup(jfIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPassword)
                        .addComponent(txtUsuario)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jfIngresoLayout.setVerticalGroup(
            jfIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfIngresoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jfIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jfIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnLogeo)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jlImUser.setText("jLabel1");

        javax.swing.GroupLayout jfFondoLayout = new javax.swing.GroupLayout(jfFondo);
        jfFondo.setLayout(jfFondoLayout);
        jfFondoLayout.setHorizontalGroup(
            jfFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfFondoLayout.createSequentialGroup()
                .addGroup(jfFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jfIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jfFondoLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jlImUser))
                    .addGroup(jfFondoLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jfFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEmpresa)
                            .addComponent(jlIniSesion))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jfFondoLayout.setVerticalGroup(
            jfFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfFondoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlEmpresa)
                .addGap(37, 37, 37)
                .addComponent(jlIniSesion)
                .addGap(43, 43, 43)
                .addComponent(jlImUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jfIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jfFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jfFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogeoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogeoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnLogeo;
<<<<<<< HEAD
    public static javax.swing.JPanel jfFondo;
=======
    private javax.swing.JPanel jfFondo;
>>>>>>> 629b0a4a0a07ad412eb64cf4714f8018caa7ca5d
    private javax.swing.JPanel jfIngreso;
    private javax.swing.JLabel jlEmpresa;
    private javax.swing.JLabel jlImUser;
    private javax.swing.JLabel jlIniSesion;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlUsuario;
    public static javax.swing.JPasswordField txtPassword;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
