/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorUser;
import static Controlador.ControladorUser.cantidad;
import static Modelo.Matrices.Tpago;
import static Modelo.Matrices.datos;
import static Modelo.Matrices.titulos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.LineBorder;

/**
 *
 * @author PC
 */
public class frmUsuario extends javax.swing.JFrame {

    private ControladorUser ctrlUser;

    public frmUsuario() {
        initComponents();
        ctrlUser = new ControladorUser(this);
        setTitle("PANEL DE USUARIOS");
        JTable tbDatos = new JTable(datos, titulos);
        JFrame jf = new JFrame("Factura de venta");
        jf.setLayout(null);//ELIMINAMOS EL LAYOUT
        jf.setVisible(true);
        Dimension d = new Dimension();
        JScrollPane scroll = new JScrollPane();

        //jf.setVisible(true);
        //Cabecera
        lblTitulo.setText("Factura de venta");
        lblEmpresa.setText("Restaurantes de Cali");
        lblDirEmpresa.setText("Carrera 46 C 49 - 66");
        lblCiudad.setText("Santiago de Cali");
        lblTelEmpresa.setText("301 750 88 33");
        //Datos
        lblCC.setText("Cedula: ");
        txtCC.setText("");
        txtCC.setPreferredSize(new Dimension(150, 30));
        lblName.setText("Nombre Completo: ");
        txtName.setText("");
        txtName.setPreferredSize(new Dimension(150, 30));
        lblTel.setText("Telefono: ");
        txtTel.setText("");
        txtTel.setPreferredSize(new Dimension(150, 30));
        lblDir.setText("Direccion: ");
        txtDir.setText("");
        txtDir.setPreferredSize(new Dimension(150, 30));
        lblPago.setText("Forma de pago");

        //Jpanel de la Foto
        lblFoto.setText("");
        lblFoto.setToolTipText("Aqui va foto del cliente");
        jfFoto.setBorder(new LineBorder(Color.black));
        //configuracion boton FileChooser
        btnFoto.setText("");
        btnFoto.setToolTipText("Carga la foto");
        ImageIcon oriCam = new ImageIcon(getClass().getResource("/imgs/camera.png"));
        Image EscalCam = oriCam.getImage().getScaledInstance(24, 24, Image.SCALE_DEFAULT);
        btnFoto.setIcon(new ImageIcon(EscalCam));
        //btnFoto.addActionListener(ctrlUser);
        //configuracion boton aceptar
        btnAceptar.setText("");
        ImageIcon origA = new ImageIcon(getClass().getResource("/imgs/aceptar.png"));
        Image EscalA = origA.getImage().getScaledInstance(24, 24, Image.SCALE_DEFAULT);
        btnAceptar.setIcon(new ImageIcon(EscalA));
        btnAceptar.setToolTipText("Aceptar");
        //configuracion boton limpiar
        btnClean.setText("");
        ImageIcon origC = new ImageIcon(getClass().getResource("/imgs/clean.png"));
        Image EscalC = origC.getImage().getScaledInstance(24, 24, Image.SCALE_DEFAULT);
        btnClean.setIcon(new ImageIcon(EscalC));
        btnClean.setToolTipText("Limpiar busqueda");
        //configuracion boton nuevo
        btnNuevo.setText("");
        ImageIcon origN = new ImageIcon(getClass().getResource("/imgs/nuevo.png"));
        Image EscalN = origN.getImage().getScaledInstance(24, 24, Image.SCALE_DEFAULT);
        btnNuevo.setIcon(new ImageIcon(EscalN));
        btnNuevo.setToolTipText("Nueva Busqueda");
        //configuracion boton salir
        btnSalir.setText("");
        ImageIcon origS = new ImageIcon(getClass().getResource("/imgs/salir.png"));
        Image EscalS = origS.getImage().getScaledInstance(24, 24, Image.SCALE_DEFAULT);
        btnSalir.setIcon(new ImageIcon(EscalS));
        btnSalir.setToolTipText("Salir");

        //Configuracion boton buscar
        btnBuscar.setText("");
        ImageIcon origB = new ImageIcon(getClass().getResource("/imgs/buscar.png"));
        Image EscalB = origB.getImage().getScaledInstance(24, 24, Image.SCALE_DEFAULT);
        btnBuscar.setIcon(new ImageIcon(EscalB));
        btnBuscar.setToolTipText("Buscar");
        //btnBuscar.addActionListener(ctrlUser);
        //definir titulo tabla

        //definir jcombobox
        pago.removeAllItems();
        for (String forma : Tpago) {
            pago.addItem(forma);
        };
        //opcion de que las cabezas sean estaticas
        scroll.setViewportView(tbDatos);
        //posicion de la tabla
        scroll.setBounds(10, 330, 685, 150);
        //posicion de la grilla
        jf.add(scroll);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf = new javax.swing.JPanel();
        jfCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblDirEmpresa = new javax.swing.JLabel();
        lblTelEmpresa = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        jfFoto = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        jfDatos = new javax.swing.JPanel();
        lblCC = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblDir = new javax.swing.JLabel();
        txtCC = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pago = new javax.swing.JComboBox<>();
        lblPago = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("jLabel1");

        lblEmpresa.setText("jLabel1");

        lblDirEmpresa.setText("jLabel1");

        lblTelEmpresa.setText("jLabel1");

        lblCiudad.setText("jLabel1");

        javax.swing.GroupLayout jfCabeceraLayout = new javax.swing.GroupLayout(jfCabecera);
        jfCabecera.setLayout(jfCabeceraLayout);
        jfCabeceraLayout.setHorizontalGroup(
            jfCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblEmpresa)
                    .addComponent(lblDirEmpresa)
                    .addComponent(lblTelEmpresa)
                    .addComponent(lblCiudad))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jfCabeceraLayout.setVerticalGroup(
            jfCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDirEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCiudad)
                .addContainerGap())
        );

        lblFoto.setText("jLabel1");

        btnFoto.setText("jButton1");

        javax.swing.GroupLayout jfFotoLayout = new javax.swing.GroupLayout(jfFoto);
        jfFoto.setLayout(jfFotoLayout);
        jfFotoLayout.setHorizontalGroup(
            jfFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addGroup(jfFotoLayout.createSequentialGroup()
                        .addComponent(btnFoto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jfFotoLayout.setVerticalGroup(
            jfFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFoto)
                .addContainerGap())
        );

        lblCC.setText("jLabel1");

        lblName.setText("jLabel2");

        lblTel.setText("jLabel3");

        lblDir.setText("jLabel4");

        txtCC.setText("jTextField1");

        txtName.setText("jTextField2");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtTel.setText("jTextField3");

        txtDir.setText("jTextField4");

        btnBuscar.setText("jButton1");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPago.setText("jLabel5");

        javax.swing.GroupLayout jfDatosLayout = new javax.swing.GroupLayout(jfDatos);
        jfDatos.setLayout(jfDatosLayout);
        jfDatosLayout.setHorizontalGroup(
            jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblName)
                        .addGap(27, 27, 27))
                    .addGroup(jfDatosLayout.createSequentialGroup()
                        .addGroup(jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDir, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfDatosLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblPago)
                        .addGap(18, 18, 18)
                        .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jfDatosLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        jfDatosLayout.setVerticalGroup(
            jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCC)
                    .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jfDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDir)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPago))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDatos);

        btnNuevo.setText("jButton1");

        btnClean.setText("jButton2");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        btnAceptar.setText("jButton3");

        btnSalir.setText("jButton4");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfLayout = new javax.swing.GroupLayout(jf);
        jf.setLayout(jfLayout);
        jfLayout.setHorizontalGroup(
            jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jfLayout.createSequentialGroup()
                        .addGroup(jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(jfFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jfLayout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnClean)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAceptar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jfLayout.setVerticalGroup(
            jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfLayout.createSequentialGroup()
                        .addComponent(jfCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jfDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jfFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnClean)
                    .addComponent(btnSalir)
                    .addComponent(btnAceptar))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    public static javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnClean;
    public static javax.swing.JButton btnFoto;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jf;
    private javax.swing.JPanel jfCabecera;
    private javax.swing.JPanel jfDatos;
    private javax.swing.JPanel jfFoto;
    private javax.swing.JLabel lblCC;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblDirEmpresa;
    private javax.swing.JLabel lblEmpresa;
    public static javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTelEmpresa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JComboBox<String> pago;
    private javax.swing.JTable tbDatos;
    public static javax.swing.JTextField txtCC;
    public static javax.swing.JTextField txtDir;
    public static javax.swing.JTextField txtName;
    public static javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
